services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-app
    environment:
      DATABASE_URI: ${DATABASE_URI}
    ports:
      - "5001:5001"
    command: ["sh", "-c", "flask db upgrade && gunicorn --bind 0.0.0.0:5001 app:app"]
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-app
    ports:
      - "3001:3001"
    depends_on:
      - server

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: